### ISSUE TITLE
.fasta link broken

### ISSUE THREAD

**Issue by nathanjohns** [jbisanz/HuVirDB#1]
I just tried downloading the HuVirdb database and the https://opengut.ucsf.edu/HuVirDB-1.0.fasta.gz link gives a server not responding error. Please let me know if there is another place to download the file.

**Comment by jbisanz** [comment]
Hi Nathan,
My apologies but our public-facing lab server is currently not available due to an aggravating IT issue. I am currently uploading the data to dryad and will update the link once the upload is done.
Jordan

**Comment by jbisanz** [comment]
The download should be available at https://doi.org/10.7272/Q6FX77PX shortly. Let me know if you have any issues getting it!

**Comment by jbisanz** [comment]
I was just following up on this and saw the doi isn't active yet. I believe this temporary link should have you set until it is: https://datadryad.org/stash/share/FFgso-zbU5koKFlnlxTy4dVnY72pmOH6Auhe0dtLCXg

**Comment by nathanjohns** [comment]
Thanks, I just got it to work although decompressing it on my AWS instance created some strange files, for example "0?share=FFgso-zbU5koKFlnlxTy4dVnY72pmOH6Auhe0dtLCXg ", "i????J???n9?d??6l?8?F??#??:?B??<Kݦ??P?`󸮛?yj?q0??Y?Xe???+????????0.9X??????P'm??U???%??????????", and "???0????$?BnK??". I still was able to get the .fasta file but I figured I would let you know this weird quirk.

**Comment by nathanjohns** [comment]
I repeated this for the hell of it and I think the weird files were a result of me attempting the wrong decompression command (tar vs unzip) at first because the file resulting from using wget doesn't have a file extension. It behaved normally this time when I used unzip.

**Comment by jbisanz** [comment]
Thanks for the heads up, I think dryad has snuck in some additional files which will hopefully be less cryptically named when the deposit is finalized.
